spring:
  application:
    name: eureka
  config:
    import: configserver:http://localhost:8888
  main:
    allow-bean-definition-overriding: true
server:
  port: 8090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka