spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mysql
    username: root
    url: jdbc:mysql://localhost:3307/projectdb
  application:
    name: inventoryapp
server:
  port: 8002
