version: "3"
services:
  currency-exchange:
    build: ./currency-exchange
    ports:
      - "8090:8090"
    networks:
      - conversion-network

  currency-conversion:
    build: ./currency-conversion
    ports:
      - "8070:8070"
    depends_on:
      - currency-exchange
    networks:
      - conversion-network

networks:
  conversion-network:
