spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rachelpark818181@gmail.com
    password: kbvtzfqwplurnjun
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: rachelpark181818@gmail.com

  application:
  name: notificationapp
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: event:com.demo.orderapp.entity.Order
server:
  port: 8004
